package com.ishapps.dev.twitterclone.util

val DATA_USERS = "Users"
val DATA_USER_EMAIL = "email"
val DATA_USER_USERNAME = "username"
val DATA_USER_IMAGE_URL = "imageUrl"
val DATA_USER_HASHTAGS = "followhashtags"
val DATA_USER_FOLLOW = "followUsers"
val DATA_IMAGES = "profileimages"
val DATA_TWEETS = "tweets"
val DATA_TWEET_USER_IDS="userIds"
val DATA_TWEET_HASHTAGS="hashTags"
val DATA_TWEET_LIKES = "likes"
val DATA_TWEET_IMAGES = "tweetImages"
val DATA_TWEET_IMAGE_URLS="tweetImageUrl"
